// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'C:/Users/arvin/Desktop/project/node_modules/dumi/theme-default/slots/Footer/index.js';
